# Generated by Django 5.2.6 on 2025-10-20 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0002_rename_running_time_song_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='album',
            name='unique_album_per_artist_format',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default='no_cover.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Hidden'), (1, 'Unlisted'), (2, 'Public')], default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='position',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('artist_name', 'title', 'format'), name='unique_album_artist_format_title'),
        ),
    ]
