# Generated by Django 5.2.6 on 2025-10-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0003_remove_album_unique_album_per_artist_format_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='length',
            new_name='running_time',
        ),
    ]
