# Generated by Django 5.2.6 on 2025-10-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0004_rename_length_song_running_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='running_time',
            new_name='length',
        ),
    ]
