# Generated by Django 5.2.6 on 2025-11-05 14:18

import django.core.validators
import django.db.models.deletion
import dottify.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0005_rename_running_time_song_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='album',
            name='unique_album_artist_format_title',
        ),
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_song_per_album',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist_account',
        ),
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='song',
            name='position',
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dottify.song'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dottify.dottifyuser'),
        ),
        migrations.AddField(
            model_name='rating',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dottify.song'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dottify.dottifyuser'),
        ),
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default=dottify.models.default_cover, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='format',
            field=models.CharField(choices=[('ALB', 'Album'), ('SNGL', 'Single'), ('EP', 'EP')], default='ALB', max_length=8),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dottifyuser',
            name='display_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_set', to='dottify.dottifyuser'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='dottify.song'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Unlisted'), (2, 'Public')], default=2),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dottify.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
