# Generated by Django 5.2.6 on 2025-11-06 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0006_alter_song_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dottify.playlist'),
        ),
        migrations.AddField(
            model_name='rating',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dottify.album'),
        ),
    ]
