# Generated by Django 5.2.6 on 2025-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0007_comment_playlist_rating_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='format',
            field=models.CharField(choices=[('SNGL', 'Single'), ('RMST', 'Remaster'), ('DLUX', 'Deluxe Edition'), ('COMP', 'Compilation'), ('LIVE', 'Live Recording')], default='ALB', max_length=8),
        ),
    ]
