# Generated by Django 5.2.6 on 2025-12-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0009_rating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='format',
            field=models.CharField(blank=True, choices=[('SNGL', 'Single'), ('RMST', 'Remaster'), ('DLUX', 'Deluxe Edition'), ('COMP', 'Compilation'), ('LIVE', 'Live Recording')], max_length=8, null=True),
        ),
    ]
